---
common:
  system_packages:
    - python-apt
    - python-pip
    - python-setuptools
    - supervisor
    - git-core
    - jq
    - python-pip 
    - git 
    - build-essential 
    - python-dev 
    - redis-server

  python_packages:
    - virtualenv
